### ISSUE TITLE
php 7.3 issue

### ISSUE THREAD

**Issue by bryce13950** [barryvdh/laravel-dompdf#543]
Same issue as this #503. Seems like its an issue with dompdf. Now that PHP 7.3 is in production, the underlying library should be updated.

**Comment by bryce13950** [comment]
Once 0.8.3 is released then this library can be updated https://github.com/dompdf/dompdf/milestone/10

The specific issue is this one https://github.com/dompdf/dompdf/issues/1822

**Comment by bryce13950** [comment]
That specific issue has been fixed.

**Comment by bryce13950** [comment]
dompdf has been updated, and this is now fixed.

**Comment by Rogierownage** [comment]
@bryce13950 This is not actually fixed. The latest version of barryvdh/laravel-dompdf still requires dompdf/dompdf @ v0.8 rather than 0.8.3. This error still happens as a result.

As you can see here:
https://github.com/barryvdh/laravel-dompdf/blob/3fd817065e1c820b1ddace8b2bf65ca45088df4f/composer.json#L15

**Comment by dmtar** [comment]
@Rogierownage You have to update your laravel-dompdf dependency with the following command:

    composer update barryvdh/laravel-dompdf --with-dependencies

--with-dependencies flag will update the the dompdf/dompdf dependency to v0.8.3
