### ISSUE TITLE
round(): Argument #1 ($num) must be of type int|float, string given error

### ISSUE THREAD

**Issue by Nizaralmohammad** [barryvdh/laravel-dompdf#757]
When I try download pdf after render like this:

        $pdf = PDF::loadView('storeapis::pdfStore', ['products' => $products, 'store' => $store, 'image' => $image]);

        return $pdf->download('products.pdf');

PHP 8 and Laravel 8
error:
 "message": "round(): Argument #1 ($num) must be of type int|float, string given",
    "exception": "TypeError",
    "file": "/Users/nizaralmohammad/Sites/tree-with-layout/vendor/dompdf/dompdf/src/Css/Style.php",
    "line": 3321,
    "trace": [
        {
            "file": "/Users/nizaralmohammad/Sites/tree-with-layout/vendor/dompdf/dompdf/src/Css/Style.php",
            "line": 3321,
            "function": "round"
        },
        {
            "file": "/Users/nizaralmohammad/Sites/tree-with-layout/vendor/dompdf/dompdf/src/Css/Style.php",
            "line": 894,
            "function": "set_z_index",
            "class": "Dompdf\\Css\\Style",
            "type": "->"
        },
        {
            "file": "/Users/nizaralmohammad/Sites/tree-with-layout/vendor/dompdf/dompdf/src/Css/Stylesheet.php",
            "line": 1638,
            "function": "__set",
            "class": "Dompdf\\Css\\Style",
            "type": "->"
        },
        {
            "file": "/Users/nizaralmohammad/Sites/tree-with-layout/vendor/dompdf/dompdf/src/Css/Stylesheet.php",
            "line": 1671,
            "function": "_parse_properties",
            "class": "Dompdf\\Css\\Stylesheet",
            "type": "->"
        },
        {
            "file": "/Users/nizaralmohammad/Sites/tree-with-layout/vendor/dompdf/dompdf/src/Css/Stylesheet.php",
            "line": 1415,
            "function": "_parse_sections",
            "class": "Dompdf\\Css\\Stylesheet",
            "type": "->"
        },
        {
            "file": "/Users/nizaralmohammad/Sites/tree-with-layout/vendor/dompdf/dompdf/src/Css/Stylesheet.php",
            "line": 420,
            "function": "_parse_css",
            "class": "Dompdf\\Css\\Stylesheet",
            "type": "->"
        },
        {
            "file": "/Users/nizaralmohammad/Sites/tree-with-layout/vendor/dompdf/dompdf/src/Dompdf.php",
            "line": 649,
            "function": "load_css_file",
            "class": "Dompdf\\Css\\Stylesheet",
            "type": "->"
        },
        {
            "file": "/Users/nizaralmohammad/Sites/tree-with-layout/vendor/dompdf/dompdf/src/Dompdf.php",
            "line": 761,
            "function": "processHtml",
            "class": "Dompdf\\Dompdf",
            "type": "->"
        },
        {
            "file": "/Users/nizaralmohammad/Sites/tree-with-layout/vendor/barryvdh/laravel-dompdf/src/PDF.php",
            "line": 208,
            "function": "render",
            "class": "Dompdf\\Dompdf",
            "type": "->"
        },
        {
            "file": "/Users/nizaralmohammad/Sites/tree-with-layout/vendor/barryvdh/laravel-dompdf/src/PDF.php",
            "line": 155,
            "function": "render",
            "class": "Barryvdh\\DomPDF\\PDF",
            "type": "->"
        },
        {
            "file": "/Users/nizaralmohammad/Sites/tree-with-layout/vendor/barryvdh/laravel-dompdf/src/PDF.php",
            "line": 178,
            "function": "output",
            "class": "Barryvdh\\DomPDF\\PDF",
            "type": "->"
        },

**Comment by socieboy** [comment]
I have the same problem. any fix on that?

**Comment by asbrito** [comment]
I also have the same problem.

**Comment by webissupport** [comment]
This might not be ideal but this is working and did not came across any with a side issue yet: on line 3321 of the Style.php script cats the $val variable to integer: round((int)$val)

**Comment by lenomosh** [comment]
On Style.php on line 3321
change `round($val)` to `round((int)$val)`
In my case it was on line 3304
So it is better to find the following statement
```
        if (round($val) != $val && $val !== "auto") {
            return;
        }
```
and change it to 
```
        if (round((int)$val) != $val && $val !== "auto") {
            return;
        }
```

**Comment by sandinur157** [comment]
please, check your php version.
I also have the same problem if I use php v.8 , but after I swicth to version 7 the problem was resolved

**Comment by JuanDeLeon** [comment]
Worked for me after upgrading to 0.9.0
This was my **composer update** log:

- Downloading dompdf/dompdf (v1.0.2)
  - Downloading barryvdh/laravel-dompdf (v0.9.0)
  - Upgrading dompdf/dompdf (v0.8.6 => v1.0.2): Extracting archive
  - Upgrading barryvdh/laravel-dompdf (v0.8.7 => v0.9.0): Extracting archive

**Comment by andbulavkin** [comment]
Changing `Style.php` brings another error

`Unsupported operand types: string + float`

**Comment by carletonm** [comment]
This seems to be an issue that occurs with php 8. They need to fix the style.php file and change round($val) to round((int)$val). As lenomosh said.

**Comment by aromka** [comment]
Also occurs with PHP 7 if you use strict types. Is there an update on this?

**Comment by charliedearce** [comment]
its working on php v7.4.22

**Comment by shakethatweight-simon** [comment]
This has been fixed in dompdf with a better solution than the ones posted above.

Can you confirm when the fixed version will be included in Wordpress.

https://github.com/dompdf/dompdf/issues/2670

**Comment by nizigama** [comment]
> On Style.php on line 3321 change `round($val)` to `round((int)$val)` In my case it was on line 3304 So it is better to find the following statement
> 
> ```
>         if (round($val) != $val && $val !== "auto") {
>             return;
>         }
> ```
> 
> and change it to
> 
> ```
>         if (round((int)$val) != $val && $val !== "auto") {
>             return;
>         }
> ```

**NEVER EVER CHANGE VENDOR FILES EVER!!!!!!!!!!!!!!!!!!!!!!!!**

**Comment by agitnaeta** [comment]
I still have issue here, 
using php 8.0 
apache 2.4.53
 "laravel/framework": "^8.12",
  "barryvdh/laravel-dompdf": "^0.8.7",

**Comment by nizigama** [comment]
> I still have issue here, using php 8.0 apache 2.4.53 "laravel/framework": "^8.12", "barryvdh/laravel-dompdf": "^0.8.7",

What issue? can you explain more about your issue

**Comment by saleh-khalaf** [comment]
i have same issue with php7.4 and doing `        if (round((int)$val) != $val && $val !== "auto") {
            return;
        }` fixed the issue but shows a unorganized pdf

**Comment by saleh-khalaf** [comment]
> i have same issue with php7.4 and doing ` if (round((int)$val) != $val && $val !== "auto") { return; }` fixed the issue but shows a unorganized pdf

i reinstall php7.4 and now all working fine
